#!/usr/bin/env bash
# Install DevFlow's Claude skills (and the pi subset); all conflicts are checked before writing.
set -euo pipefail
export PYTHONDONTWRITEBYTECODE=1
DEVFLOW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${DEVFLOW_CLAUDE_DIR:-$HOME/.claude}"
BIN_DIR="${DEVFLOW_BIN_DIR:-$HOME/.local/bin}"
INTEGRATIONS_DIR="${DEVFLOW_INTEGRATIONS_DIR:-$HOME/.config/devflow/integrations}"
POLICY_FILE="${DEVFLOW_MODEL_POLICY:-$CLAUDE_DIR/devflow/model-policy.json}"
STATUSLINE="${DEVFLOW_STATUSLINE:-$CLAUDE_DIR/statusline.sh}"
PI_DIR="${DEVFLOW_PI_DIR:-$HOME/.pi/agent}"
# Every skills/<name>/SKILL.md declares `pi:` in its frontmatter: `true` → linked into pi, a quoted reason → skipped.
SKILLS=()
for src in "$DEVFLOW_DIR"/skills/*/SKILL.md; do
    SKILLS+=("$(basename "$(dirname "$src")")")
done
pi_field() { awk 'NR>1 && /^---$/{exit} /^pi:/{sub(/^pi:[ \t]*/, ""); gsub(/^["'"'"']|["'"'"']$/, ""); print; exit}' "$1"; }
LINKED_AGENTS=(review-standards review-conformance crossreview reader browser)
AGENT_MARKER='generated by devflow install.sh from model-policy.json'
PYTHON="$DEVFLOW_DIR/.venv/bin/python"
RETIRED_SKILLS=(research plan implement quick)
issues=0
mode=install
case "${1:-}" in
    --check) mode=check ;;
    --remove) mode=remove ;;
    '') ;;
    *) echo "Usage: $0 [--check|--remove]" >&2; exit 1 ;;
esac
[ "$#" -le 1 ] || { echo 'Too many arguments' >&2; exit 1; }
# The venv lives in DEVFLOW_DIR, so creating it before preflight writes nothing into the user's directories.
if [ "$mode" = install ]; then
    python3 -c 'import sys; assert sys.version_info >= (3, 10), "Python 3.10+ required"'
    if [ ! -x "$PYTHON" ]; then
        python3 -m venv --system-site-packages "$DEVFLOW_DIR/.venv"
    fi
    if ! "$PYTHON" -c 'import yaml' 2>/dev/null; then
        "$PYTHON" -m pip install -r "$DEVFLOW_DIR/requirements.txt"
    fi
fi

sources=() destinations=()
for name in "${SKILLS[@]}"; do
    sources+=("$DEVFLOW_DIR/skills/$name")
    destinations+=("$CLAUDE_DIR/skills/$name")
done
for name in "${LINKED_AGENTS[@]}"; do
    sources+=("$DEVFLOW_DIR/agents/$name.md")
    destinations+=("$CLAUDE_DIR/agents/$name.md")
done
pi_skipped=()
for name in "${SKILLS[@]}"; do
    value="$(pi_field "$DEVFLOW_DIR/skills/$name/SKILL.md")"
    if [ "$value" = true ]; then
        sources+=("$DEVFLOW_DIR/skills/$name" "$DEVFLOW_DIR/pi/prompts/$name.md")
        destinations+=("$PI_DIR/skills/$name" "$PI_DIR/prompts/$name.md")
    elif [ -n "$value" ] && [ "$value" != false ]; then
        pi_skipped+=("skip pi $name: $value")
    else
        echo "MISS pi field in skills/$name/SKILL.md" >&2; issues=1
    fi
done
for entry in scripts/devflow-cli.sh:devflow bin/lcurl:lcurl bin/devflow-browser:devflow-browser \
    bin/devflow-smoke-wait:devflow-smoke-wait bin/devflow-pi:devflow-pi scripts/rate-limits.sh:devflow-rate-limits; do
    sources+=("$DEVFLOW_DIR/${entry%%:*}")
    destinations+=("$BIN_DIR/${entry#*:}")
done
for src in "$DEVFLOW_DIR"/integrations/jira-*.sh; do
    sources+=("$src")
    destinations+=("$INTEGRATIONS_DIR/$(basename "$src")")
done
sources+=("$DEVFLOW_DIR/integrations/config.env.template")
destinations+=("$INTEGRATIONS_DIR/config.env.template")

links_to() { [ -L "$1" ] && [ "$(readlink "$1")" = "$2" ]; }
for i in "${!sources[@]}"; do
    src="${sources[$i]}" dst="${destinations[$i]}"
    if [ "$mode" = remove ]; then
        if links_to "$dst" "$src"; then
            rm -- "$dst"
            echo "unlink $dst"
        fi
    elif [ ! -e "$src" ]; then
        echo "MISS source: $src" >&2; issues=1
    elif links_to "$dst" "$src"; then
        echo "ok $dst"
    elif [ -e "$dst" ] || [ -L "$dst" ]; then
        echo "CONFLICT (not replacing): $dst" >&2; issues=1
    elif [ "$mode" = check ]; then
        echo "MISS $dst"; issues=1
    fi
done
# Phase agents are generated, not linked: the policy decides which names exist and which files are ours
# (marker or an old symlink to agents/<phase>.md); anything else under those names is foreign.
if [ "$mode" = remove ]; then
    generated_agent() { [ -f "$1" ] && [ ! -L "$1" ] && grep -qF -- "$AGENT_MARKER" "$1"; }
    for dst in "$CLAUDE_DIR"/agents/*.md; do
        [ -e "$dst" ] || [ -L "$dst" ] || continue
        name="$(basename "$dst" .md)"
        if generated_agent "$dst" || links_to "$dst" "$DEVFLOW_DIR/agents/${name%%-*}.md"; then
            rm -- "$dst"
            echo "remove $dst"
        fi
    done
elif [ -x "$PYTHON" ]; then
    preflight_policy="$POLICY_FILE"
    [ -e "$preflight_policy" ] || preflight_policy="$DEVFLOW_DIR/model-policy.example.json"
    conflicts="$(DEVFLOW_MODEL_POLICY="$preflight_policy" PYTHONPATH="$DEVFLOW_DIR/scripts" "$PYTHON" -m devflow.policy conflicts "$CLAUDE_DIR/agents")" || issues=1
    while IFS= read -r dst; do
        [ -n "$dst" ] || continue
        echo "CONFLICT (not replacing): $dst" >&2; issues=1
    done <<< "$conflicts"
fi
if [ "$mode" != remove ]; then
    for line in "${pi_skipped[@]}"; do
        echo "$line"
    done
fi

if [ "$mode" = check ]; then
    if [ ! -x "$PYTHON" ]; then
        echo 'MISS Python environment; run ./install.sh'; issues=1
    elif ! "$PYTHON" -c 'import sys, yaml; assert sys.version_info >= (3, 10)' 2>/dev/null; then
        echo 'MISS Python 3.10+ / PyYAML'; issues=1
    fi
    for name in "${RETIRED_SKILLS[@]}"; do
        if links_to "$CLAUDE_DIR/skills/$name" "$DEVFLOW_DIR/skills/$name"; then
            echo "RETIRE $CLAUDE_DIR/skills/$name"; issues=1
        fi
    done
    if [ -x "$PYTHON" ]; then
        if ! "$PYTHON" -c 'import sys; from pathlib import Path; sys.path.insert(0, sys.argv[1] + "/scripts"); from devflow.project import registry_path; from devflow.registry import load; p = registry_path(Path(sys.argv[1])); p.exists() or sys.exit("MISS project registry"); load(p)' \
            "$DEVFLOW_DIR"; then
            issues=1
        fi
    fi
    if [ ! -e "$POLICY_FILE" ]; then
        echo "MISS model policy $POLICY_FILE"; issues=1
    elif [ -x "$PYTHON" ]; then
        echo "ok $POLICY_FILE"
        stale="$(DEVFLOW_MODEL_POLICY="$POLICY_FILE" PYTHONPATH="$DEVFLOW_DIR/scripts" "$PYTHON" -m devflow.policy stale "$CLAUDE_DIR/agents")" || issues=1
        for name in $(DEVFLOW_MODEL_POLICY="$POLICY_FILE" PYTHONPATH="$DEVFLOW_DIR/scripts" "$PYTHON" -m devflow.policy names); do
            grep -qxF -- "STALE agent $name" <<<"$stale" || echo "ok $CLAUDE_DIR/agents/$name.md"
        done
        if [ -n "$stale" ]; then
            echo "$stale"; issues=1
        fi
    fi
    # statusline.sh is the user's own file: the one-line hook (README, "Rate limits") is pasted by hand.
    if [ -f "$STATUSLINE" ] && ! grep -q 'devflow-rate-limits' "$STATUSLINE"; then
        echo 'MISS statusline call devflow-rate-limits'; issues=1
    fi
    if [ -x "$PYTHON" ]; then
        drift="$("$PYTHON" -c 'import sys; sys.path.insert(0, sys.argv[1])
from devflow.project import guard_probe, settings_drift
for c in guard_probe(sys.argv[2]): print("BROKEN global hook PreToolUse", c)
d = settings_drift(sys.argv[2], sys.argv[3])
for c in d["hooks"]: print("MISS global hook", c)
for p in d["allow"]: print("MISS global allow", p)
for p in d["ask"]: print("MISS global ask", p)
for p in d["deny"]: print("MISS global deny", p)
for p in d["extra_deny"]: print("STALE global deny", p)
for k in d["keys"]: print("MISS global setting", k)' \
            "$DEVFLOW_DIR/scripts" "$CLAUDE_DIR/settings.json" "$DEVFLOW_DIR/settings.global.example.json")" || issues=1
        if [ -n "$drift" ]; then
            echo "$drift"; issues=1
            echo "(merge settings.global.example.json into $CLAUDE_DIR/settings.json by hand; __DEVFLOW_ROOT__ = $DEVFLOW_DIR)"
        fi
    fi
    echo '(check mode — no changes made)'
    exit "$issues"
fi
[ "$issues" -eq 0 ] || exit 1

if [ "$mode" = install ]; then
    "$PYTHON" -c 'import sys; from pathlib import Path; sys.path.insert(0, sys.argv[1] + "/scripts"); from devflow.registry import initialize; initialize(Path(sys.argv[1]))' "$DEVFLOW_DIR"
    mkdir -p "$CLAUDE_DIR/skills" "$CLAUDE_DIR/agents" "$PI_DIR/skills" "$PI_DIR/prompts" "$BIN_DIR" "$INTEGRATIONS_DIR"
    for i in "${!sources[@]}"; do
        src="${sources[$i]}" dst="${destinations[$i]}"
        if links_to "$dst" "$src"; then
            continue
        fi
        # No force: if a destination appeared after preflight, stop without replacing it.
        ln -sT -- "$src" "$dst"
        echo "link $dst"
    done
    if [ ! -e "$POLICY_FILE" ]; then
        mkdir -p "$(dirname "$POLICY_FILE")"
        cp -- "$DEVFLOW_DIR/model-policy.example.json" "$POLICY_FILE"
        echo "copy $POLICY_FILE"
    fi
    # Phase agents are rendered from model-policy.json (frontmatter) + agents/<phase>.md (body); atomic write.
    DEVFLOW_MODEL_POLICY="$POLICY_FILE" PYTHONPATH="$DEVFLOW_DIR/scripts" "$PYTHON" -m devflow.policy write "$CLAUDE_DIR/agents"
fi
for name in "${RETIRED_SKILLS[@]}"; do
    dst="$CLAUDE_DIR/skills/$name"
    if links_to "$dst" "$DEVFLOW_DIR/skills/$name"; then
        rm -- "$dst"
        echo "retire $dst"
    fi
done
echo "DevFlow $mode complete. Project state and registry are preserved on removal."
