#!/usr/bin/env bash
# Install DevFlow's Claude skills (and the pi subset); all conflicts are checked before writing.
set -euo pipefail
export PYTHONDONTWRITEBYTECODE=1
DEVFLOW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_DIR="${DEVFLOW_CLAUDE_DIR:-$HOME/.claude}"
BIN_DIR="${DEVFLOW_BIN_DIR:-$HOME/.local/bin}"
INTEGRATIONS_DIR="${DEVFLOW_INTEGRATIONS_DIR:-$HOME/.config/devflow/integrations}"
POLICY_FILE="${DEVFLOW_MODEL_POLICY:-$CLAUDE_DIR/devflow/model-policy.json}"
STATUSLINE="${DEVFLOW_STATUSLINE:-$CLAUDE_DIR/statusline.sh}"
SKILLS=(note project devflow standup tokens page review jira jira-create xreview timesheet cut transcribe smoke)
PI_DIR="${DEVFLOW_PI_DIR:-$HOME/.pi/agent}"
PI_SKILLS=(note jira project cut devflow)
PI_PROMPTS=(note jira project cut devflow)
# Skills not linked into pi: name → reason (needs Claude Code subagents, or not verified there).
# devflow is linked: in pi it launches phases through `devflow phase run` instead of Agent.
PI_SKIPPED=(
    "review: uses Agent/SendMessage"
    "tokens: uses Agent"
    "standup: not verified for pi"
    "xreview: not verified for pi"
    "jira-create: not verified for pi"
    "timesheet: not verified for pi"
    "page: not verified for pi"
    "transcribe: not verified for pi"
    "smoke: needs a Claude Code subagent; in pi run the saved script"
)
[ ! -d "$DEVFLOW_DIR/skills/autoresearch" ] || SKILLS+=(autoresearch)
LINKED_AGENTS=(review-standards review-conformance crossreview reader browser)
AGENT_MARKER='generated by devflow install.sh from model-policy.json'
PYTHON="$DEVFLOW_DIR/.venv/bin/python"
RETIRED_SKILLS=(research plan implement quick)
mode=install
case "${1:-}" in
    --check) mode=check ;;
    --remove) mode=remove ;;
    '') ;;
    *) echo "Usage: $0 [--check|--remove]" >&2; exit 1 ;;
esac
[ "$#" -le 1 ] || { echo 'Too many arguments' >&2; exit 1; }

sources=() destinations=()
for name in "${SKILLS[@]}"; do
    sources+=("$DEVFLOW_DIR/skills/$name")
    destinations+=("$CLAUDE_DIR/skills/$name")
done
for name in "${LINKED_AGENTS[@]}"; do
    sources+=("$DEVFLOW_DIR/agents/$name.md")
    destinations+=("$CLAUDE_DIR/agents/$name.md")
done
for name in "${PI_SKILLS[@]}"; do
    sources+=("$DEVFLOW_DIR/skills/$name")
    destinations+=("$PI_DIR/skills/$name")
done
for name in "${PI_PROMPTS[@]}"; do
    sources+=("$DEVFLOW_DIR/pi/prompts/$name.md")
    destinations+=("$PI_DIR/prompts/$name.md")
done
sources+=("$DEVFLOW_DIR/scripts/devflow-cli.sh")
destinations+=("$BIN_DIR/devflow")
sources+=("$DEVFLOW_DIR/bin/lcurl")
destinations+=("$BIN_DIR/lcurl")
sources+=("$DEVFLOW_DIR/bin/devflow-browser")
destinations+=("$BIN_DIR/devflow-browser")
sources+=("$DEVFLOW_DIR/bin/devflow-smoke-wait")
destinations+=("$BIN_DIR/devflow-smoke-wait")
sources+=("$DEVFLOW_DIR/bin/devflow-pi")
destinations+=("$BIN_DIR/devflow-pi")
sources+=("$DEVFLOW_DIR/scripts/rate-limits.sh")
destinations+=("$BIN_DIR/devflow-rate-limits")
for src in "$DEVFLOW_DIR"/integrations/jira-*.sh; do
    sources+=("$src")
    destinations+=("$INTEGRATIONS_DIR/$(basename "$src")")
done
sources+=("$DEVFLOW_DIR/integrations/config.env.template")
destinations+=("$INTEGRATIONS_DIR/config.env.template")

issues=0
for i in "${!sources[@]}"; do
    src="${sources[$i]}" dst="${destinations[$i]}"
    if [ "$mode" = remove ]; then
        if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
            rm -- "$dst"
            echo "unlink $dst"
        fi
    elif [ ! -e "$src" ]; then
        echo "MISS source: $src" >&2; issues=1
    elif [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
        echo "ok $dst"
    elif [ -e "$dst" ] || [ -L "$dst" ]; then
        echo "CONFLICT (not replacing): $dst" >&2; issues=1
    elif [ "$mode" = check ]; then
        echo "MISS $dst"; issues=1
    fi
done
# Phase agents (research/plan/implement[-high]) are generated, not linked: an old symlink to our source or a marked file may be replaced; anything else is foreign.
generated_agent() { [ -f "$1" ] && [ ! -L "$1" ] && grep -qF -- "$AGENT_MARKER" "$1"; }
phase_agent_source() { local phase="${1%%-*}"; echo "$DEVFLOW_DIR/agents/$phase.md"; }
for dst in "$CLAUDE_DIR"/agents/*.md; do
    [ -e "$dst" ] || [ -L "$dst" ] || continue
    name="$(basename "$dst" .md)"
    case "$name" in research|research-high|plan|plan-high|implement|implement-high) ;; *) continue ;; esac
    if [ "$mode" = remove ]; then
        if generated_agent "$dst" || { [ -L "$dst" ] && [ "$(readlink "$dst")" = "$(phase_agent_source "$name")" ]; }; then
            rm -- "$dst"
            echo "remove $dst"
        fi
    elif generated_agent "$dst" || { [ -L "$dst" ] && [ "$(readlink "$dst")" = "$(phase_agent_source "$name")" ]; }; then
        :
    else
        echo "CONFLICT (not replacing): $dst" >&2; issues=1
    fi
done
if [ "$mode" != remove ]; then
    for entry in "${PI_SKIPPED[@]}"; do
        echo "skip pi ${entry%%:*}:${entry#*:}"
    done
fi

if [ "$mode" = check ]; then
    if [ ! -x "$PYTHON" ]; then
        echo 'MISS Python environment; run ./install.sh'; issues=1
    elif ! "$PYTHON" -c 'import sys, yaml; assert sys.version_info >= (3, 10)' 2>/dev/null; then
        echo 'MISS Python 3.10+ / PyYAML'; issues=1
    fi
    if [ -x "$PYTHON" ]; then
        if ! "$PYTHON" -c 'import sys; from pathlib import Path; sys.path.insert(0, sys.argv[1] + "/scripts"); from devflow.project import registry_path; from devflow.registry import load; p = registry_path(Path(sys.argv[1])); p.exists() or sys.exit("MISS project registry"); load(p)' \
            "$DEVFLOW_DIR"; then
            issues=1
        fi
    fi
    for name in "${RETIRED_SKILLS[@]}"; do
        dst="$CLAUDE_DIR/skills/$name"
        if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$DEVFLOW_DIR/skills/$name" ]; then
            echo "RETIRE $dst"; issues=1
        fi
    done
    if [ ! -e "$POLICY_FILE" ]; then
        echo "MISS model policy $POLICY_FILE"; issues=1
    elif [ -x "$PYTHON" ]; then
        echo "ok $POLICY_FILE"
        stale="$(DEVFLOW_MODEL_POLICY="$POLICY_FILE" PYTHONPATH="$DEVFLOW_DIR/scripts" "$PYTHON" -m devflow.policy stale "$CLAUDE_DIR/agents")" || issues=1
        for name in $(DEVFLOW_MODEL_POLICY="$POLICY_FILE" PYTHONPATH="$DEVFLOW_DIR/scripts" "$PYTHON" -m devflow.policy names); do
            case "$stale" in *"STALE agent $name"*) ;; *) echo "ok $CLAUDE_DIR/agents/$name.md" ;; esac
        done
        if [ -n "$stale" ]; then
            echo "$stale"; issues=1
        fi
    fi
    # statusline.sh is the user's own file: the one-line hook (README, "Rate limits") is pasted by hand.
    if [ -f "$STATUSLINE" ] && ! grep -q 'devflow-rate-limits' "$STATUSLINE"; then
        echo 'MISS statusline call devflow-rate-limits'; issues=1
    fi
    if [ -x "$PYTHON" ]; then
        drift="$("$PYTHON" -c 'import sys; sys.path.insert(0, sys.argv[1])
from devflow.project import guard_probe, settings_drift
for c in guard_probe(sys.argv[2]): print("BROKEN global hook PreToolUse", c)
d = settings_drift(sys.argv[2], sys.argv[3])
for c in d["hooks"]: print("MISS global hook", c)
for p in d["allow"]: print("MISS global allow", p)
for p in d["ask"]: print("MISS global ask", p)
for p in d["deny"]: print("MISS global deny", p)
for p in d["extra_deny"]: print("STALE global deny", p)' \
            "$DEVFLOW_DIR/scripts" "$CLAUDE_DIR/settings.json" "$DEVFLOW_DIR/settings.global.example.json")" || issues=1
        if [ -n "$drift" ]; then
            echo "$drift"; issues=1
            echo "(merge settings.global.example.json into $CLAUDE_DIR/settings.json by hand; __DEVFLOW_ROOT__ = $DEVFLOW_DIR)"
        fi
    fi
    echo '(check mode — no changes made)'
    exit "$issues"
fi
[ "$issues" -eq 0 ] || exit 1

if [ "$mode" = install ]; then
    python3 -c 'import sys; assert sys.version_info >= (3, 10), "Python 3.10+ required"'
    if [ ! -x "$DEVFLOW_DIR/.venv/bin/python" ]; then
        python3 -m venv --system-site-packages "$DEVFLOW_DIR/.venv"
    fi
    if ! "$PYTHON" -c 'import yaml' 2>/dev/null; then
        "$PYTHON" -m pip install -r "$DEVFLOW_DIR/requirements.txt"
    fi
    "$PYTHON" -c 'import sys; from pathlib import Path; sys.path.insert(0, sys.argv[1] + "/scripts"); from devflow.registry import initialize; initialize(Path(sys.argv[1]))' "$DEVFLOW_DIR"
    mkdir -p "$CLAUDE_DIR/skills" "$CLAUDE_DIR/agents" "$PI_DIR/skills" "$PI_DIR/prompts" "$BIN_DIR" "$INTEGRATIONS_DIR"
    for i in "${!sources[@]}"; do
        src="${sources[$i]}" dst="${destinations[$i]}"
        if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$src" ]; then
            continue
        fi
        # No force: if a destination appeared after preflight, stop without replacing it.
        ln -sT -- "$src" "$dst"
        echo "link $dst"
    done
    if [ ! -e "$POLICY_FILE" ]; then
        mkdir -p "$(dirname "$POLICY_FILE")"
        cp -- "$DEVFLOW_DIR/model-policy.example.json" "$POLICY_FILE"
        echo "copy $POLICY_FILE"
    fi
    # Phase agents are rendered from model-policy.json (frontmatter) + agents/<phase>.md (body); atomic write.
    DEVFLOW_MODEL_POLICY="$POLICY_FILE" PYTHONPATH="$DEVFLOW_DIR/scripts" "$PYTHON" -m devflow.policy write "$CLAUDE_DIR/agents"
fi
for name in "${RETIRED_SKILLS[@]}"; do
    dst="$CLAUDE_DIR/skills/$name"
    if [ -L "$dst" ] && [ "$(readlink "$dst")" = "$DEVFLOW_DIR/skills/$name" ]; then
        rm -- "$dst"
        echo "retire $dst"
    fi
done
echo "DevFlow $mode complete. Project state and registry are preserved on removal."
