"""Model/effort policy: host × phase × complexity → {model, effort}, read from a user-editable JSON."""
import json
import os
import re
import sys
import time
from pathlib import Path

from .documents import WorkflowError
from .storage import atomic_write

REQUIRED = ('claude', 'pi', 'limits')
PHASES = ('research', 'plan', 'implement')
SOURCE_DIR = Path(__file__).resolve().parents[2] / 'agents'
MARKER = '<!-- generated by devflow install.sh from model-policy.json; edit agents/{phase}.md -->'
MARKER_KEY = 'generated by devflow install.sh from model-policy.json'
ALIASES = {'claude-opus-': 'opus', 'claude-fable-': 'fable', 'claude-sonnet-': 'sonnet', 'claude-haiku-': 'haiku'}


def claude_dir():
    return Path(os.environ.get('DEVFLOW_CLAUDE_DIR', str(Path.home() / '.claude')))


def policy_path():
    return Path(os.environ.get('DEVFLOW_MODEL_POLICY', str(claude_dir() / 'devflow/model-policy.json')))


def load(path):
    if not path.exists():
        return None
    try:
        policy = json.loads(path.read_text())
    except (json.JSONDecodeError, UnicodeDecodeError) as e:
        raise WorkflowError(f'Model policy is not valid JSON: {path}: {e}')
    missing = [k for k in REQUIRED if not isinstance(policy, dict) or k not in policy]
    if missing:
        raise WorkflowError(f'Model policy {path} lacks keys: ' + ', '.join(missing))
    incomplete = [f'{host}/{phase}' for host in ('claude', 'pi') for phase in PHASES
                  if not isinstance(policy[host], dict) or 'default' not in policy[host].get(phase, {})]
    if incomplete:
        raise WorkflowError(f'Model policy {path} has no default column for: ' + ', '.join(incomplete))
    return policy


def resolve(policy, host, phase, complexity=None, exhausted=False):
    phases = policy.get(host)
    if not isinstance(phases, dict) or phase not in phases:
        raise WorkflowError(f'Model policy has no entry for {host}/{phase}')
    columns = phases[phase]
    if 'default' not in columns:
        raise WorkflowError(f'Model policy {host}/{phase} has no default column')
    if exhausted and 'fallback' in columns:
        column = 'fallback'
    elif complexity == 'high' and 'high' in columns:
        column = 'high'
    else:
        column = 'default'
    entry = columns[column]
    return {'model': entry['model'], 'effort': entry['effort'], 'column': column}


def alias(model_id):
    for prefix, name in ALIASES.items():
        if model_id.startswith(prefix):
            return name
    return None


def pi_model(entry):
    return entry['model'] + (':' + entry['effort'] if entry.get('effort') else '')


def limits_path():
    return Path(os.environ.get('DEVFLOW_RATE_LIMITS', str(claude_dir() / 'devflow/rate-limits.json')))


def limits(path, threshold, max_age_min, now):
    """rate-limits.json → {exhausted, window, used_percentage, resets_at, at}; None if absent, stale or broken."""
    path = Path(path)
    if not path.is_file():
        return None
    try:
        data = json.loads(path.read_text())
    except (json.JSONDecodeError, UnicodeDecodeError):
        return None
    at = data.get('at') if isinstance(data, dict) else None
    if not isinstance(at, (int, float)) or now - at > max_age_min * 60:
        return None
    windows = [(name, w['used_percentage'], w.get('resets_at')) for name in ('five_hour', 'seven_day')
               if isinstance(w := data.get(name), dict) and isinstance(w.get('used_percentage'), (int, float))]
    if not windows:
        return {'exhausted': False, 'window': None, 'used_percentage': None, 'resets_at': None, 'at': at}

    def blown(pct, resets_at):
        return pct >= threshold and isinstance(resets_at, (int, float)) and now < resets_at

    name, pct, resets_at = max(windows, key=lambda w: (blown(w[1], w[2]), w[1]))
    return {'exhausted': blown(pct, resets_at), 'window': name, 'used_percentage': pct, 'resets_at': resets_at, 'at': at}


def agents_dir():
    return claude_dir() / 'agents'


def agent_names(policy):
    """`<phase>` per phase, plus `<phase>-high` when that column differs and `<phase>-fallback` when its effort differs.

    A fallback that changes only the model needs no agent: the driver passes the model alias at spawn time.
    """
    names = []
    for phase in PHASES:
        columns = policy['claude'][phase]
        names.append(phase)
        if 'high' in columns and columns['high'] != columns['default']:
            names.append(phase + '-high')
        if 'fallback' in columns and columns['fallback']['effort'] != columns['default']['effort']:
            names.append(phase + '-fallback')
    return names


def render_agent(policy, name, source_dir=SOURCE_DIR):
    phase, _, suffix = name.partition('-')
    entry = policy['claude'][phase][suffix or 'default']
    text = (source_dir / f'{phase}.md').read_text()
    m = re.match(r'---\n(.*?)\n---\n', text, re.S)
    if not m:
        raise WorkflowError(f'Agent source has no frontmatter: {source_dir / phase}.md')
    fields = {'name': name, 'model': entry['model'], 'effort': entry['effort']}
    lines = [f'{k}: {fields.pop(k)}' if (k := line.split(':', 1)[0]) in fields else line
             for line in m.group(1).split('\n')]
    lines += [f'{k}: {v}' for k, v in fields.items()]
    return '---\n' + '\n'.join(lines) + '\n---\n' + MARKER.format(phase=phase) + '\n' + text[m.end():]


def installed_stale(policy, directory=None, source_dir=SOURCE_DIR):
    directory = agents_dir() if directory is None else Path(directory)
    stale = []
    for name in agent_names(policy):
        dst = directory / f'{name}.md'
        if not dst.is_file() or dst.read_text() != render_agent(policy, name, source_dir):
            stale.append(name)
    return stale


def is_generated(path):
    path = Path(path)
    return path.is_file() and not path.is_symlink() and MARKER_KEY in path.read_text()


def write_agents(policy, directory, source_dir=SOURCE_DIR):
    directory = Path(directory)
    directory.mkdir(parents=True, exist_ok=True)
    for name in agent_names(policy):
        dst = directory / f'{name}.md'
        content = render_agent(policy, name, source_dir)
        if dst.is_file() and not dst.is_symlink() and dst.read_text() == content:
            yield name, 'ok'
            continue
        atomic_write(dst, content)
        yield name, 'generate'


def launch(phase, complexity=None, now=None):
    """`policy`, `limits` + `launch` fields for `route`; only `policy: None` when no policy file is installed."""
    path = policy_path()
    policy = load(path)
    if policy is None:
        return {'policy': None}
    cfg = policy['limits']
    signal = limits(limits_path(), cfg.get('threshold', 95), cfg.get('max_age_min', 10), time.time() if now is None else now)
    exhausted = bool(signal and signal['exhausted'])
    claude = resolve(policy, 'claude', phase, complexity, exhausted)
    pi = resolve(policy, 'pi', phase, complexity, exhausted)
    agent = f"{phase}-{claude['column']}" if f"{phase}-{claude['column']}" in agent_names(policy) else phase
    model = (alias(claude['model']) or claude['model']) if claude['column'] == 'fallback' else None
    return {'policy': str(path),
            'limits': signal,
            'policy_stale': installed_stale(policy),
            'launch': {'claude': {'id': claude['model'], 'effort': claude['effort'], 'model': model, 'agent': agent},
                       'pi': {'model': pi_model(pi)}}}


def main(argv):
    policy = load(policy_path())
    if policy is None:
        sys.exit(f'MISS model policy {policy_path()}')
    command, args = argv[0], argv[1:]
    if command == 'names':
        print('\n'.join(agent_names(policy)))
    elif command == 'write':
        for name, action in write_agents(policy, args[0]):
            print(f'{action} {Path(args[0]) / name}.md')
    elif command == 'stale':
        for name in installed_stale(policy, args[0]):
            print(f'STALE agent {name}')
    else:
        sys.exit(f'Unknown policy command: {command}')


if __name__ == '__main__':
    main(sys.argv[1:])
